"""
German cities data for autocomplete
"""

# Список найбільших міст Німеччини
MAJOR_GERMAN_CITIES = [
    'Berlin',
    'Hamburg',
    'München',
    'Köln',
    'Frankfurt am Main',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hannover',
    'Nürnberg',
    'Duisburg',
    'Bochum',
    'Wuppertal',
    'Bielefeld',
    'Bonn',
    'Münster',
    'Karlsruhe',
    'Mannheim',
    'Augsburg',
    'Wiesbaden',
    'Gelsenkirchen',
    'Mönchengladbach',
    'Braunschweig',
    'Kiel',
    'Chemnitz',
    'Aachen',
    'Halle',
    'Magdeburg',
    'Freiburg im Breisgau',
    'Krefeld',
    'Lübeck',
    'Oberhausen',
    'Erfurt',
    'Mainz',
    'Rostock',
    'Kassel',
    'Hagen',
    'Hamm',
    'Saarbrücken',
    'Mülheim an der Ruhr',
    'Potsdam',
    'Ludwigshafen am Rhein',
    'Oldenburg',
    'Leverkusen',
    'Osnabrück',
    'Solingen',
    'Heidelberg',
    'Herne',
    'Neuss',
    'Darmstadt',
    'Paderborn',
    'Regensburg',
    'Ingolstadt',
    'Würzburg',
    'Fürth',
    'Wolfsburg',
    'Offenbach am Main',
    'Ulm',
    'Heilbronn',
    'Pforzheim',
    'Göttingen',
    'Bottrop',
    'Trier',
    'Recklinghausen',
    'Reutlingen',
    'Bremerhaven',
    'Koblenz',
    'Bergisch Gladbach',
    'Jena',
    'Remscheid',
    'Erlangen',
    'Moers',
    'Siegen',
    'Hildesheim',
    'Salzgitter',
]

# Bundesländer для фільтрації
GERMAN_STATES = {
    'Baden-Württemberg': ['Stuttgart', 'Mannheim', 'Karlsruhe', 'Freiburg im Breisgau', 'Heidelberg', 'Ulm', 'Heilbronn', 'Pforzheim', 'Reutlingen'],
    'Bayern': ['München', 'Nürnberg', 'Augsburg', 'Regensburg', 'Ingolstadt', 'Würzburg', 'Fürth', 'Erlangen'],
    'Berlin': ['Berlin'],
    'Brandenburg': ['Potsdam'],
    'Bremen': ['Bremen', 'Bremerhaven'],
    'Hamburg': ['Hamburg'],
    'Hessen': ['Frankfurt am Main', 'Wiesbaden', 'Kassel', 'Darmstadt', 'Offenbach am Main'],
    'Mecklenburg-Vorpommern': ['Rostock'],
    'Niedersachsen': ['Hannover', 'Braunschweig', 'Oldenburg', 'Osnabrück', 'Wolfsburg', 'Göttingen', 'Salzgitter', 'Hildesheim'],
    'Nordrhein-Westfalen': ['Köln', 'Düsseldorf', 'Dortmund', 'Essen', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Münster', 'Gelsenkirchen', 'Mönchengladbach', 'Aachen', 'Krefeld', 'Oberhausen', 'Hagen', 'Hamm', 'Mülheim an der Ruhr', 'Leverkusen', 'Solingen', 'Herne', 'Neuss', 'Paderborn', 'Bottrop', 'Recklinghausen', 'Bergisch Gladbach', 'Remscheid', 'Moers', 'Siegen'],
    'Rheinland-Pfalz': ['Mainz', 'Ludwigshafen am Rhein', 'Koblenz', 'Trier'],
    'Saarland': ['Saarbrücken'],
    'Sachsen': ['Leipzig', 'Dresden', 'Chemnitz'],
    'Sachsen-Anhalt': ['Halle', 'Magdeburg'],
    'Schleswig-Holstein': ['Kiel', 'Lübeck'],
    'Thüringen': ['Erfurt', 'Jena'],
}
