"""Make Doctor.practice_id NOT NULL for tenant isolation

Revision ID: 1eb8c2797e5b
Revises: create_admin_table
Create Date: 2026-02-04 19:29:10.894711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1eb8c2797e5b'
down_revision = 'create_admin_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('admins', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_terminfinder_admins_username'), ['username'], unique=True)

    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('total_bookings', sa.Integer(), nullable=True),
    sa.Column('no_show_count', sa.Integer(), nullable=True),
    sa.Column('late_cancellations', sa.Integer(), nullable=True),
    sa.Column('early_cancellations', sa.Integer(), nullable=True),
    sa.Column('attended_appointments', sa.Integer(), nullable=True),
    sa.Column('notification_email', sa.Boolean(), nullable=True),
    sa.Column('notification_sms', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('patients', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_patients_phone'), ['phone'], unique=True)

    op.create_table('practices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=False),
    sa.Column('handelsregister_nr', sa.String(length=50), nullable=True),
    sa.Column('owner_email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('google_business_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('opening_hours', sa.Text(), nullable=True),
    sa.Column('social_media', sa.Text(), nullable=True),
    sa.Column('photos', sa.Text(), nullable=True),
    sa.Column('gallery_photos', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('virtual_tour_url', sa.String(length=500), nullable=True),
    sa.Column('services', sa.Text(), nullable=True),
    sa.Column('team_members', sa.Text(), nullable=True),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('accepted_insurances', sa.Text(), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('faq', sa.Text(), nullable=True),
    sa.Column('rating_avg', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('parking_info', sa.Text(), nullable=True),
    sa.Column('public_transport', sa.Text(), nullable=True),
    sa.Column('emergency_phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('meta_title', sa.String(length=200), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('chatbot_instructions', sa.Text(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('total_appointments', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('practices', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_practices_owner_email'), ['owner_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_practices_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_terminfinder_practices_vat_number'), ['vat_number'], unique=True)

    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('tax_number', sa.String(length=50), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('speciality', sa.String(length=50), nullable=False),
    sa.Column('speciality_custom', sa.String(length=100), nullable=True),
    sa.Column('speciality_approved', sa.Boolean(), nullable=True),
    sa.Column('languages', sa.Text(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('previous_positions', sa.Text(), nullable=True),
    sa.Column('treatment_focus', sa.Text(), nullable=True),
    sa.Column('subspecialities', sa.Text(), nullable=True),
    sa.Column('professional_memberships', sa.Text(), nullable=True),
    sa.Column('publications', sa.Text(), nullable=True),
    sa.Column('consultation_types', sa.Text(), nullable=True),
    sa.Column('video_consultation_url', sa.String(length=500), nullable=True),
    sa.Column('hobbies', sa.Text(), nullable=True),
    sa.Column('motto', sa.String(length=500), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=True),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('work_days', sa.Text(), nullable=False),
    sa.Column('work_start_time', sa.Time(), nullable=False),
    sa.Column('work_end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['terminfinder.practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('doctors', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_doctors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_terminfinder_doctors_practice_id'), ['practice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_doctors_speciality'), ['speciality'], unique=False)

    op.create_table('calendar_integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('oauth_access_token', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token', sa.Text(), nullable=True),
    sa.Column('oauth_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('oauth_scope', sa.String(length=500), nullable=True),
    sa.Column('caldav_url', sa.String(length=500), nullable=True),
    sa.Column('caldav_username', sa.String(length=200), nullable=True),
    sa.Column('caldav_password', sa.Text(), nullable=True),
    sa.Column('caldav_calendar_id', sa.String(length=200), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_direction', sa.String(length=20), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error_message', sa.Text(), nullable=True),
    sa.Column('sync_error_count', sa.Integer(), nullable=False),
    sa.Column('external_webhook_id', sa.String(length=200), nullable=True),
    sa.Column('external_resource_id', sa.String(length=200), nullable=True),
    sa.Column('webhook_expires_at', sa.DateTime(), nullable=True),
    sa.Column('event_title_template', sa.String(length=200), nullable=False),
    sa.Column('event_description_template', sa.Text(), nullable=False),
    sa.Column('event_color_id', sa.String(length=10), nullable=True),
    sa.Column('event_reminders', sa.Boolean(), nullable=False),
    sa.Column('import_free_busy', sa.Boolean(), nullable=False),
    sa.Column('import_event_titles', sa.Boolean(), nullable=False),
    sa.Column('auto_block_conflicts', sa.Boolean(), nullable=False),
    sa.Column('external_calendar_name', sa.String(length=200), nullable=True),
    sa.Column('external_calendar_timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['terminfinder.doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('calendar_integrations', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_calendar_integrations_doctor_id'), ['doctor_id'], unique=False)

    op.create_table('calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('working_hours', sa.Text(), nullable=False),
    sa.Column('slot_duration', sa.Integer(), nullable=False),
    sa.Column('buffer_time', sa.Integer(), nullable=False),
    sa.Column('max_advance_booking_days', sa.Integer(), nullable=True),
    sa.Column('min_advance_booking_hours', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['terminfinder.doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('calendars', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_calendars_doctor_id'), ['doctor_id'], unique=True)

    op.create_table('patient_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('speciality', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('date_from', sa.Date(), nullable=True),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(), nullable=True),
    sa.Column('last_slot_notified_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['terminfinder.doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['terminfinder.patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('patient_alerts', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_patient_alerts_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_patient_alerts_patient_id'), ['patient_id'], unique=False)

    op.create_table('time_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calendar_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('block_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['terminfinder.calendars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('time_slots', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_time_slots_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_time_slots_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_time_slots_status'), ['status'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timeslot_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=100), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('booking_code', sa.String(length=8), nullable=False),
    sa.Column('cancellable_until', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=20), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['terminfinder.patients.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['terminfinder.time_slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_intent_id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('bookings', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_bookings_booking_code'), ['booking_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_terminfinder_bookings_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_bookings_timeslot_id'), ['timeslot_id'], unique=True)

    op.create_table('practice_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('rating_overall', sa.Integer(), nullable=False),
    sa.Column('rating_treatment', sa.Integer(), nullable=True),
    sa.Column('rating_staff', sa.Integer(), nullable=True),
    sa.Column('rating_facilities', sa.Integer(), nullable=True),
    sa.Column('rating_waiting_time', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flagged_reason', sa.String(length=500), nullable=True),
    sa.Column('practice_response', sa.Text(), nullable=True),
    sa.Column('practice_response_at', sa.DateTime(), nullable=True),
    sa.Column('practice_response_by', sa.UUID(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('not_helpful_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['terminfinder.bookings.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['terminfinder.doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['terminfinder.patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['terminfinder.practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='terminfinder'
    )
    with op.batch_alter_table('practice_reviews', schema='terminfinder') as batch_op:
        batch_op.create_index(batch_op.f('ix_terminfinder_practice_reviews_doctor_id'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_practice_reviews_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminfinder_practice_reviews_practice_id'), ['practice_id'], unique=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('ix_admins_email')
        batch_op.drop_index('ix_admins_username')

    op.drop_table('admins')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name='alembic_version_pkc')
    )
    op.create_table('admins',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('two_factor_secret', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('account_locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index('ix_admins_username', ['username'], unique=True)
        batch_op.create_index('ix_admins_email', ['email'], unique=True)

    with op.batch_alter_table('practice_reviews', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_practice_reviews_practice_id'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_practice_reviews_patient_id'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_practice_reviews_doctor_id'))

    op.drop_table('practice_reviews', schema='terminfinder')
    with op.batch_alter_table('bookings', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_bookings_timeslot_id'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_bookings_patient_id'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_bookings_booking_code'))

    op.drop_table('bookings', schema='terminfinder')
    with op.batch_alter_table('time_slots', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_time_slots_status'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_time_slots_start_time'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_time_slots_calendar_id'))

    op.drop_table('time_slots', schema='terminfinder')
    with op.batch_alter_table('patient_alerts', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_patient_alerts_patient_id'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_patient_alerts_doctor_id'))

    op.drop_table('patient_alerts', schema='terminfinder')
    with op.batch_alter_table('calendars', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_calendars_doctor_id'))

    op.drop_table('calendars', schema='terminfinder')
    with op.batch_alter_table('calendar_integrations', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_calendar_integrations_doctor_id'))

    op.drop_table('calendar_integrations', schema='terminfinder')
    with op.batch_alter_table('doctors', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_doctors_speciality'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_doctors_practice_id'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_doctors_email'))

    op.drop_table('doctors', schema='terminfinder')
    with op.batch_alter_table('practices', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_practices_vat_number'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_practices_slug'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_practices_owner_email'))

    op.drop_table('practices', schema='terminfinder')
    with op.batch_alter_table('patients', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_patients_phone'))

    op.drop_table('patients', schema='terminfinder')
    with op.batch_alter_table('admins', schema='terminfinder') as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminfinder_admins_username'))
        batch_op.drop_index(batch_op.f('ix_terminfinder_admins_email'))

    op.drop_table('admins', schema='terminfinder')
    # ### end Alembic commands ###
