"""Make practice_id nullable for doctors

Revision ID: 9ef6c9f1ee44
Revises: 63ba08f885d8
Create Date: 2026-01-28 21:21:56.805075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef6c9f1ee44'
down_revision = '63ba08f885d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only make practice_id nullable for doctors table
    with op.batch_alter_table('doctors', schema='terminfinder') as batch_op:
        batch_op.alter_column('practice_id', nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make practice_id NOT NULL again for doctors table
    with op.batch_alter_table('doctors', schema='terminfinder') as batch_op:
        batch_op.alter_column('practice_id', nullable=False)

    # ### end Alembic commands ###
